# Generated by Django 4.0.4 on 2022-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_stamp', models.CharField(max_length=500)),
                ('open', models.CharField(max_length=500)),
                ('high', models.CharField(max_length=500)),
                ('low', models.CharField(max_length=500)),
                ('close', models.CharField(max_length=500)),
            ],
        ),
    ]
