# Generated by Django 4.0.5 on 2022-07-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Crypto',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(max_length=500)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.CharField(max_length=500)),
                ('low', models.CharField(max_length=500)),
                ('close', models.CharField(max_length=500)),
                ('volume', models.CharField(max_length=500, null=True)),
                ('market_cap', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('currency', models.CharField(max_length=500, null=True)),
                ('currency_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.crypto')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddIndex(
            model_name='detail',
            index=models.Index(fields=['time_stamp', 'open', 'high', 'low', 'close', 'volume', 'market_cap', 'created_at'], name='main_detail_time_st_984e59_idx'),
        ),
    ]
