# Generated by Django 4.0.5 on 2022-07-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Crypto',
                'ordering': ('pk',),
            },
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='market_cap',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='volume',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AddIndex(
            model_name='detail',
            index=models.Index(fields=['time_stamp', 'open', 'high', 'low', 'close', 'created_at'], name='main_detail_time_st_629c58_idx'),
        ),
        migrations.AddField(
            model_name='detail',
            name='currency_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.crypto'),
        ),
    ]
