# Generated by Django 4.0.4 on 2022-07-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crypto_alter_detail_options_detail_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='name',
        ),
        migrations.AddField(
            model_name='crypto',
            name='crypto',
            field=models.CharField(choices=[('BTS', 'Bitcoin'), ('ETH', 'Etherium'), ('SOL', 'Solana')], default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='detail',
            name='currency_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.crypto'),
        ),
    ]
