# Generated by Django 4.0.4 on 2022-07-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crypto_alter_detail_options_detail_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
