# Generated by Django 4.0.5 on 2022-07-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_crypto_name_crypto_crypto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={},
        ),
        migrations.RemoveField(
            model_name='detail',
            name='currency_name',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='crypto',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Etherium'), ('SOL', 'Solana')], default='', max_length=512),
        ),
    ]
